### ISSUE TITLE
Unable to run yarn test

### ISSUE THREAD

**Issue by icdev2dev** [seniorjoinu/ic-cron#3]
On ubuntu 20.04, dfx : 0.8.4

yarn test
yarn run v1.22.15
$ ts-mocha --paths --timeout 1000000 src/**/*.spec.ts

Error: Cannot find module 'dfx-idl/ic-cron-example/ic-cron-example'

-----------------------------------------------------------------------------------------------------------------------------------------

yarn start seems to work in the prior step

yarn start
yarn run v1.22.15
$ dfx start --clean
Starting webserver for /_/
binding to: 127.0.0.1:39575
....
Dec 06 20:21:06.604 WARN s:gj7o2-tv6sz-egnnq-zjllt-paj4g-zlonj-jr7u5-bt632-5ymwn-g46ly-sae/n:zxe2u-fcrwj-jrji2-laj6m-xskov-ti2t4-nxped-teak3-qj4wg-jftrt-6qe/ic_state_layout/utils StateManager runs on a filesystem not supporting reflinks (attempted to reflink /home/xyz/src/ic/ic-cron/example/e2e-test/.dfx/state/replicated_state/node-100/state/tip/system_metadata.pbuf => /home/xyz/src/ic/ic-cron/example/e2e-test/.dfx/state/replicated_state/node-100/state/fs_tmp/scratchpad_0000000000000064/system_metadata.pbuf), running big canisters can be very slow

**Comment by seniorjoinu** [comment]
I've updated the readme.

You now need to also run `yarn build` after `yarn start`.
The whole sequence is:

* `yarn start` in a separate terminal
* `yarn build`
* `yarn test`
