### ISSUE TITLE
IC-Cron Service

### ISSUE THREAD

**Issue by domwoe** [seniorjoinu/ic-cron#5]
Hey @seniorjoinu,

have you considered deploying a service based on this to the IC where canisters can register themselves (against a few) to be notified?

Would be cool to have economically self-sufficient service like this on the IC :)

**Comment by seniorjoinu** [comment]
Hey @domwoe,
Sorry for being inactive for such a long time.

Would you pay for such a service? 
And if you would, then, how much?

**Comment by seniorjoinu** [comment]
I believe, with DeTi this issue is no longer actual.
